/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Product {
  id: number;
  name?: string;
  provider?: string;
  description: string;
  stock?: string;
  price?: number;
  allergy?: string;
}
